# NAME: Nikola Samardzic
# EMAIL: nikola.s@ucla.edu
# ID: 904799099

build:
	gcc -Wall -Wextra lab3a.c -o lab3a
clean:
	rm -rf lab3a
	rm -rf lab3a-904799099.tar.gz

dist: build 
	tar -cvzf lab3a-904799099.tar.gz README lab3a.c ext2_fs.h Makefile

