# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.2_AR71275_op
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado/2018.2.op2258646/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcvu9p-flgb2104-2-i ../xilinx_com_hls_digitrec_kernel_1_0.zip
