# NAME: Nikola Samardzic
# EMAIL: nikola.s@ucla.edu
# ID: 904799099

main: lab1a.c
	gcc -Wall -Wextra lab1a.c -o lab1a	
clean:
	rm -rf lab1a;
	rm -rf lab1a-904799099.tar.gz;
dist: main
	tar -czvf lab1a-904799099.tar.gz lab1a.c README Makefile
