catch {::common::set_param -quiet hls.xocc.mode csynth};
catch {::common::set_param -quiet hls.xocc.enable_rule_check_client 1};
# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project digitrec_kernel
set_top digitrec_kernel
add_files "/home/centos/src/project_data/aws-fpga/SDAccel/examples/xilinx_2018.2/getting_started/cs-259-18f/hw2/digitrec.cpp" -cflags " "
open_solution solution
set_part xcvu9p-flgb2104-2-i
create_clock -period 250MHz -name default
config_sdx -target xocc -optimization_level $xocc_optimize_level
config_dataflow -strict_mode warning
set_clock_uncertainty 27.000000%
config_interface -m_axi_addr64
csynth_design
export_design -format ipxact -kernel_drc -sdaccel -ipname digitrec_kernel
close_project
puts "Vivado HLS completed successfully"
exit
