// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2_AR71275_op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdigitrec_kernel_digitrec_kernel.h"

extern XDigitrec_kernel_digitrec_kernel_Config XDigitrec_kernel_digitrec_kernel_ConfigTable[];

XDigitrec_kernel_digitrec_kernel_Config *XDigitrec_kernel_digitrec_kernel_LookupConfig(u16 DeviceId) {
	XDigitrec_kernel_digitrec_kernel_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDIGITREC_KERNEL_DIGITREC_KERNEL_NUM_INSTANCES; Index++) {
		if (XDigitrec_kernel_digitrec_kernel_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDigitrec_kernel_digitrec_kernel_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDigitrec_kernel_digitrec_kernel_Initialize(XDigitrec_kernel_digitrec_kernel *InstancePtr, u16 DeviceId) {
	XDigitrec_kernel_digitrec_kernel_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDigitrec_kernel_digitrec_kernel_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDigitrec_kernel_digitrec_kernel_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

