// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2_AR71275_op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of test_image
//        bit 31~0 - test_image[31:0] (Read/Write)
// 0x14 : Data signal of test_image
//        bit 31~0 - test_image[63:32] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of train_images
//        bit 31~0 - train_images[31:0] (Read/Write)
// 0x20 : Data signal of train_images
//        bit 31~0 - train_images[63:32] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of knn_mat
//        bit 31~0 - knn_mat[31:0] (Read/Write)
// 0x2c : Data signal of knn_mat
//        bit 31~0 - knn_mat[63:32] (Read/Write)
// 0x30 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_ADDR_AP_CTRL           0x00
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_ADDR_GIE               0x04
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_ADDR_IER               0x08
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_ADDR_ISR               0x0c
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_ADDR_TEST_IMAGE_DATA   0x10
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_BITS_TEST_IMAGE_DATA   64
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_ADDR_TRAIN_IMAGES_DATA 0x1c
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_BITS_TRAIN_IMAGES_DATA 64
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_ADDR_KNN_MAT_DATA      0x28
#define XDIGITREC_KERNEL_DIGITREC_KERNEL_CONTROL_BITS_KNN_MAT_DATA      64

